name: Sonarqube Standard Scan
agent:
    type: Unity::metal::macmini
    image: package-ci/mac
    flavor: m1.mac
variables:
    SONARQUBE_PROJECT_KEY: ai-robotics-endpoint-ros2
commands:
    - curl https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-macosx.zip -o sonar-scanner-macosx.zip -L
    - unzip sonar-scanner-macosx.zip -d ~/sonar-scanner
    - ~/sonar-scanner/sonar-scanner-4.6.2.2472-macosx/bin/sonar-scanner -Dsonar.projectKey=$SONARQUBE_PROJECT_KEY -Dsonar.sources=. -Dsonar.host.url=$SONARQUBE_ENDPOINT_URL_PRD -Dsonar.login=$SONARQUBE_TOKEN_PRD
triggers:
    cancel_old_ci: true
    expression: |
        ((pull_request.target eq "main" OR pull_request.target eq "dev-ros2")
        AND NOT pull_request.push.changes.all match "**/*.md") OR
        (push.branch eq "main" OR push.branch eq "dev-ros2")