name: Endpoint Unit Tests
agent:
    type: Unity::VM
    image: robotics/ci-ubuntu20:latest
    flavor: i1.large
commands:
    # run unit tests and save test results in /home/bokken/build/output/Unity-Technologies/ROS-TCP-Endpoint
    - command: |
        source /opt/ros/noetic/setup.bash && echo "ROS_DISTRO == $ROS_DISTRO"
        cd .. && mkdir -p catkin_ws/src && cp -r ./ROS-TCP-Endpoint catkin_ws/src
        cd catkin_ws && catkin_make && source devel/setup.bash
        cd src/ROS-TCP-Endpoint
        python3 -m pytest --cov=. --cov-report xml:../../../ROS-TCP-Endpoint/test-results/coverage.xml --cov-report html:../../../ROS-TCP-Endpoint/test-results/coverage.html test/
    # check the test coverage
    - command: |
        linecoverage=$(head -2 test-results/coverage.xml | grep -Eo 'line-rate="[0-9]+([.][0-9]+)?"' | grep -Eo "[0-9]+([.][0-9]+)?")
        echo "Line coverage: $linecoverage"
        if (( $(echo "$linecoverage < 0.3" | bc -l) )); then exit 1; fi
triggers:
    cancel_old_ci: true
    expression: |
        (pull_request.target eq "main"  AND
        NOT pull_request.push.changes.all match "**/*.md") OR
        (pull_request.target eq "dev" AND
        NOT pull_request.push.changes.all match "**/*.md")
artifacts:
    logs:
        paths:
            - "test-results/**/*"
