name: Endpoint Unit Tests
agent:
    type: Unity::VM
    image: robotics/ci-ros2-galactic-ubuntu20:v0.0.2-916903
    flavor: i1.large
variables:
  # Coverage measured as a percentage (out of 100)
  COVERAGE_EXPECTED: 3.5
commands:
    # run unit tests and save test results in /home/bokken/build/output/Unity-Technologies/ROS-TCP-Endpoint
    - command: |
        source /opt/ros/galactic/setup.bash && echo "ROS_DISTRO == galactic"
        cd .. && mkdir -p ros_ws/src && cp -r ./ROS-TCP-Endpoint ros_ws/src
        cd ros_ws && colcon build && source install/local_setup.bash
        cd src/ROS-TCP-Endpoint
        python3 -m pytest --cov=. --cov-report xml:./test-results/coverage.xml --cov-report html:./test-results/coverage.html test/
    # check the test coverage
    - command: |
        linecoverage=$(head -2 test-results/coverage.xml | grep -Eo 'line-rate="[0-9]+([.][0-9]+)?"' | grep -Eo "[0-9]+([.][0-9]+)?")
        echo "Line coverage: $linecoverage"
        if (( $(echo "$linecoverage * 100.0 < $COVERAGE_EXPECTED" | bc -l) ));
        then echo "ERROR: Code Coverage is under threshold of $COVERAGE_EXPECTED%" && exit 1
        fi
triggers:
    cancel_old_ci: true
    expression: |
        ((pull_request.target eq "main-ros2" OR pull_request.target eq "dev-ros2")
          AND NOT pull_request.push.changes.all match "**/*.md") OR
        (push.branch eq "main-ros2" OR push.branch eq "dev-ros2")
artifacts:
    logs:
        paths:
            - "test-results/**/*"
