name: 'Stale issue handler'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  issues: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4.0.0
        id: stale
        with:
          stale-issue-message: 'This issue has been marked stale because it has been open for 30 days with no activity. Please remove the Stale label or comment on this issue, or the issue will be automatically closed in 7 days.'
          days-before-stale: 30
          days-before-pr-stale: -1
          days-before-close: 7
          exempt-issue-labels: 'blocked,must,should,keep,pinned,work-in-progress'
          close-issue-message: 'This issue has been marked stale for 7 days and will now be closed.'
      - name: Print outputs
        run: echo ${{ join(steps.stale.outputs.*, ',') }}